// tests go here; this will not be compiled when this package is used as a library
//---- main.ts ----
RobotZoo.blink()
RobotZoo.blink()
RobotZoo.blink()
RobotZoo.keepStill()
RobotZoo.goStraigt(presetSpeed.mid, 500)
RobotZoo.goBack(presetSpeed.mid, 500)
RobotZoo.keepStill()
//---- samples.ts ----
RobotZoo.toddle()
RobotZoo.keepStill()
// RobotZoo.swift()
// RobotZoo.keepStill()
RobotZoo.poke()
RobotZoo.keepStill()
RobotZoo.stroll()
RobotZoo.keepStill()
RobotZoo.lookAlound()
// RobotZoo.rush()
// RobotZoo.keepStill()